import type { LucideIcon } from "lucide-react";

import {
  AtSign,
  BookOpen,
  Box,
  Boxes,
  Calendar,
  CheckCircle2,
  ChevronDown,
  ChevronRight,
  CircleCheck,
  Compass,
  Container,
  Cpu,
  CreditCard,
  Database,
  Diamond,
  Flag,
  FlaskConical,
  Grid2x2,
  Grid3x3,
  Heart,
  HeartPulse,
  Home,
  Layers,
  LayoutGrid,
  Link2,
  LogIn,
  Mail,
  MapPin,
  Menu,
  Monitor,
  Package,
  Rocket,
  Search,
  Server,
  Settings,
  Share2,
  Shield,
  Shirt,
  ShoppingBag,
  ShoppingCart,
  Sparkles,
  Target,
  Terminal,
  TrendingUp,
  Trophy,
  Truck,
  User,
  UserPlus,
  Watch,
  X,
} from "lucide-react";

export const lucideIcons = {
  home: Home,
  compass: Compass,
  "trending-up": TrendingUp,

  "shopping-bag": ShoppingBag,
  "shopping-cart": ShoppingCart,
  package: Package,
  shirt: Shirt,
  watch: Watch,
  "credit-card": CreditCard,
  truck: Truck,

  user: User,
  "user-plus": UserPlus,
  "log-in": LogIn,

  "book-open": BookOpen,
  search: Search,
  heart: Heart,
  "heart-pulse": HeartPulse,
  sparkles: Sparkles,

  cpu: Cpu,
  database: Database,
  server: Server,
  terminal: Terminal,
  monitor: Monitor,
  rocket: Rocket,
  container: Container,
  box: Box,
  boxes: Boxes,
  layers: Layers,

  menu: Menu,
  close: X,
  "chevron-down": ChevronDown,
  "chevron-right": ChevronRight,
  settings: Settings,

  "grid-2x2": Grid2x2,
  "grid-3x3": Grid3x3,
  "layout-grid": LayoutGrid,

  "at-sign": AtSign,
  mail: Mail,
  "link-2": Link2,
  "share-2": Share2,

  "map-pin": MapPin,

  "circle-check": CircleCheck,
  "check-circle-2": CheckCircle2,
  shield: Shield,

  calendar: Calendar,
  diamond: Diamond,
  flag: Flag,
  "flask-conical": FlaskConical,
  target: Target,
  trophy: Trophy,
} satisfies Record<string, LucideIcon>;

export type LucideIconName = keyof typeof lucideIcons;
